### ISSUE TITLE
Cannot include .proto files from project dependency

### ISSUE THREAD

**Issue by onsails** [trueaccord/sbt-scalapb#1]
Hello!

We have an SBT project which consists of lots of sbt subprojects: https://github.com/actorapp/actor-platform/blob/server/event-sourcing/actor-server/project/Build.scala#L199
A project `actorPeerManager` has `user.proto` and `sequence.proto`. We need to move `sequence.proto` to another project `actorPush` to be able to share `sequence.proto` with other projects dependant on `actorPush` too. But here is a problem.

Plugin diesn't extract `sequence.proto`, and `user.proto` which contains `import "sequence.proto"` doesn't compile with an error `sequence.proto: File not found.`.

I've tried several ways to beat this problems: added `.aggregate(actorPush)` to `actorPeerManagers`, added `unmanagedResourceDirectories in Compile <+= (sourceDirectory in PB.protobufConfig)` as follows [sbt-protobuf readme](https://github.com/sbt/sbt-protobuf), experimented with `managedClasspath` setting but still no luck.

Is there a way to depend on `.proto` files from another sbt project?

**Comment by thesamet** [comment]
Basically protoc is not finding the import. You can try appending to the includePath so it searches for it:

  includePath ++= Seq("../foo/bar")

**Comment by onsails** [comment]
Thank you for quick response!
It worked: https://github.com/actorapp/actor-platform/commit/83d920055784981582e718936a78d777b0d15364

**Comment by charles-crain** [comment]
I got here from Google trying to figure out this exact issue.  The answer has changed since it was posted now that ScalaPB is using the sbt-protoc plugin.  The incantation that worked for me was:

`PB.includePaths in Compile += file("../foo/bar")`
