### ISSUE TITLE
Constant recompilation

### ISSUE THREAD

**Issue by onsails** [trueaccord/sbt-scalapb#2]
After enabling sbt-scalapb in our project (big project with lots of SBT subprojects), it started to recompile proto files each time when `compile` task is executed, even if proto files aren't changed. It causes tens of files which are dependant on classes generated by scalapb to recompile too.
We can try to fix the issue by ourselves, just point direction where should we dig, please.

**Comment by thesamet** [comment]
Thanks for reporting. We are also in a multiple sub-project config and are not experiencing this issue. I think trying to debug both might reveal what's happening. I might be able to help if you can produce a minimal project that demonstrates this problem.

**Comment by onsails** [comment]
Great. I'll take time for it.

**Comment by onsails** [comment]
Setting `logLevel` to `Level.Warn` in SBT helped to figure out that it was a problem of cyclic dependency between two Scala files which referenced scalapb-generated classes. Not an sbt-scalapb issue. Closing.
