### ISSUE TITLE
remove sbt-protobuf dependency?

### ISSUE THREAD

**Issue by xuwei-k** [trueaccord/sbt-scalapb#6]
I think sbt-protobuf is not active project. https://github.com/sbt/sbt-protobuf/issues/36
I need some fixes 
- https://github.com/sbt/sbt-protobuf/pull/29
- https://github.com/sbt/sbt-protobuf/pull/35

**Comment by thesamet** [comment]
Should be pretty easy to do - I'll look into this.

**Comment by He-Pin** [comment]
@thesamet would you add a gitter room for this project?
I think `sbt-protobuf` is not that active now too.

**Comment by thesamet** [comment]
Done

**Comment by xuwei-k** [comment]
sbt-protobuf 0.5.0 released.
https://github.com/trueaccord/sbt-scalapb/pull/7
